#!/bin/bash

python3 /home/ubuntu/admin/manage.py brewster content
python3 /home/ubuntu/admin/manage.py couture content
python3 /home/ubuntu/admin/manage.py covington content
python3 /home/ubuntu/admin/manage.py danagibson content
python3 /home/ubuntu/admin/manage.py elainesmith content
python3 /home/ubuntu/admin/manage.py exquisiterugs content
python3 /home/ubuntu/admin/manage.py galerie content
python3 /home/ubuntu/admin/manage.py hubbardtonforge content
python3 /home/ubuntu/admin/manage.py jaipurliving content
python3 /home/ubuntu/admin/manage.py jamieyoung content
python3 /home/ubuntu/admin/manage.py jffabrics content
python3 /home/ubuntu/admin/manage.py kasmir content
python3 /home/ubuntu/admin/manage.py kravet content
python3 /home/ubuntu/admin/manage.py kravetdecor content
python3 /home/ubuntu/admin/manage.py materialworks content
python3 /home/ubuntu/admin/manage.py maxwell content
python3 /home/ubuntu/admin/manage.py mindthegap content
python3 /home/ubuntu/admin/manage.py noir content
python3 /home/ubuntu/admin/manage.py oliviaquinn content
python3 /home/ubuntu/admin/manage.py peninsulahome content
python3 /home/ubuntu/admin/manage.py phillipjeffries content
python3 /home/ubuntu/admin/manage.py phillipscollection content
python3 /home/ubuntu/admin/manage.py pindler content
python3 /home/ubuntu/admin/manage.py pkaufman content
python3 /home/ubuntu/admin/manage.py poppy content
python3 /home/ubuntu/admin/manage.py port68 content
python3 /home/ubuntu/admin/manage.py premierprints content
python3 /home/ubuntu/admin/manage.py scalamandre content
python3 /home/ubuntu/admin/manage.py schumacher content
python3 /home/ubuntu/admin/manage.py seabrook content
python3 /home/ubuntu/admin/manage.py stout content
python3 /home/ubuntu/admin/manage.py surya content
python3 /home/ubuntu/admin/manage.py tempaper content
python3 /home/ubuntu/admin/manage.py york content
python3 /home/ubuntu/admin/manage.py zoffany content
