#!/bin/bash

python3 /home/ubuntu/admin/manage.py brewster tag
python3 /home/ubuntu/admin/manage.py couture tag
python3 /home/ubuntu/admin/manage.py covington tag
python3 /home/ubuntu/admin/manage.py danagibson tag
python3 /home/ubuntu/admin/manage.py elainesmith tag
python3 /home/ubuntu/admin/manage.py exquisiterugs tag
python3 /home/ubuntu/admin/manage.py galerie tag
python3 /home/ubuntu/admin/manage.py hubbardtonforge tag
python3 /home/ubuntu/admin/manage.py jaipurliving tag
python3 /home/ubuntu/admin/manage.py jamieyoung tag
python3 /home/ubuntu/admin/manage.py jffabrics tag
python3 /home/ubuntu/admin/manage.py kasmir tag
python3 /home/ubuntu/admin/manage.py kravet tag
python3 /home/ubuntu/admin/manage.py kravetdecor tag
python3 /home/ubuntu/admin/manage.py materialworks tag
python3 /home/ubuntu/admin/manage.py maxwell tag
python3 /home/ubuntu/admin/manage.py mindthegap tag
python3 /home/ubuntu/admin/manage.py noir tag
python3 /home/ubuntu/admin/manage.py oliviaquinn tag
python3 /home/ubuntu/admin/manage.py peninsulahome tag
python3 /home/ubuntu/admin/manage.py phillipjeffries tag
python3 /home/ubuntu/admin/manage.py phillipscollection tag
python3 /home/ubuntu/admin/manage.py pindler tag
python3 /home/ubuntu/admin/manage.py pkaufman tag
python3 /home/ubuntu/admin/manage.py poppy tag
python3 /home/ubuntu/admin/manage.py port68 tag
python3 /home/ubuntu/admin/manage.py premierprints tag
python3 /home/ubuntu/admin/manage.py scalamandre tag
python3 /home/ubuntu/admin/manage.py schumacher tag
python3 /home/ubuntu/admin/manage.py seabrook tag
python3 /home/ubuntu/admin/manage.py stout tag
python3 /home/ubuntu/admin/manage.py surya tag
python3 /home/ubuntu/admin/manage.py tempaper tag
python3 /home/ubuntu/admin/manage.py york tag
python3 /home/ubuntu/admin/manage.py zoffany tag
