#!/bin/bash

python3 manage.py brewster status
python3 manage.py couture status
python3 manage.py covington status
python3 manage.py danagibson status
python3 manage.py elainesmith status
python3 manage.py exquisiterugs status
python3 manage.py galerie status
python3 manage.py hubbardtonforge status
python3 manage.py jaipurliving status
python3 manage.py jamieyoung status
python3 manage.py jffabrics status
python3 manage.py kasmir status
python3 manage.py kravet status
python3 manage.py materialworks status
python3 manage.py maxwell status
python3 manage.py mindthegap status
python3 manage.py noir status
python3 manage.py oliviaquinn status
python3 manage.py peninsulahome status
python3 manage.py phillipjeffries status
python3 manage.py phillipscollection status
python3 manage.py pindler status
python3 manage.py pkaufman status
python3 manage.py poppy status
python3 manage.py port68 status
python3 manage.py premierprints status
python3 manage.py scalamandre status
python3 manage.py schumacher status
python3 manage.py seabrook status
python3 manage.py stout status
python3 manage.py surya status
python3 manage.py tempaper status
python3 manage.py york status
python3 manage.py zoffany status
